<?php

namespace Floarc\ParkingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository
{
	/**
	 * Retrieve Adress ordered by id 
	 * @return Ambigous <multitype:, \Doctrine\ORM\mixed, mixed, \Doctrine\DBAL\Driver\Statement, \Doctrine\Common\Cache\mixed>
	 */
	public function findAllOrderedById()
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT a FROM FloarcParkingBundle:Address a ORDER BY a.id ASC'
		)
		->getResult();
	}	
}
