<?php

namespace Floarc\ParkingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParkingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParkingRepository extends EntityRepository
{
	
	/**
	 * Retrieve indexable parking
	 * @return Ambigous <multitype:, \Doctrine\ORM\mixed, mixed, \Doctrine\DBAL\Driver\Statement, \Doctrine\Common\Cache\mixed>
	 */
	public function getIndexableParkingQueryBuilder()
	{
		/*
		return $this->getEntityManager()
		->createQuery(
			'SELECT p FROM FloarcParkingBundle:Parking p where p.isApproved=1 ORDER BY p.id ASC'
		);
		*/
		$qb = $this->getEntityManager()->createQueryBuilder();
		return $qb->select('p')
		->from('FloarcParkingBundle:Parking', 'p')
		->where('p.isApproved = 1')
		->orderBy('p.id', 'ASC');
	}	
}
