<?php

namespace Floarc\ParkingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeDureeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDureeRepository extends EntityRepository
{
}
