<?php

namespace Floarc\ParkingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypePlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePlaceRepository extends EntityRepository
{
}
