<?php

namespace Floarc\ParkingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeContratRepository extends EntityRepository
{
	/**
	 * Retrieve TypeContrat ordered by id
	 * @return Ambigous <multitype:, \Doctrine\ORM\mixed, mixed, \Doctrine\DBAL\Driver\Statement, \Doctrine\Common\Cache\mixed>
	 */
	public function findAllAsArray()
	{
		return $this->getEntityManager()
		->createQuery(
				'SELECT tc FROM FloarcParkingBundle:TypeContrat tc ORDER BY tc.id ASC'
		)
		->getResult();
	}	
}
